### ISSUE TITLE
Can't find the code. 😔

### ISSUE THREAD

**Issue by 5AF1** [herobd/handwriting_line_generation#1]
Was re-directed to this repo from both Paperswithcode and arxiv.org. Can't find the code anywhere.

**Comment by KevinMathewT** [comment]
Me too.

**Comment by herobd** [comment]
Sorry. Part of the code was written during an internship at Adobe. They've given the okay to release it, but it's going through legal/licensing stuff on their end right now. I'll let you know when it's here!

**Comment by herobd** [comment]
@5AF1  @KevinMathewT I've got the code and trained models up! Thanks for being patient.
