### ISSUE TITLE
Rimes Datasets

### ISSUE THREAD

**Issue by Tedonze** [herobd/handwriting_line_generation#13]
Good morning sir . I want to make an handwritten line recognition with the RIMES datasets. It is take too long to get the dataset from http://www.a2ialab.com/doku.php?id=rimes_database:start. Do you have an idea or an alternative please or can you provide me this dataset( I see you use it for your GAN )

**Comment by herobd** [comment]
The user agreement prevents me from sharing the RIMES dataset. Have you tried getting another? Like the IAM dataset?

**Comment by Tedonze** [comment]
I have trained my model with IAM dataset but it is not in french . So prediction on french document doesn't work great. It seems that Rimes is the best for french language. I have no more idea.

**Comment by herobd** [comment]
Both the IAM and RIMES  were collected under very specific conditions and models trained on them don't neccesarily generalize to "real world" data. Depending on your use case, you might be better off collecting your own dataset (things like Amazon Mechanical Turk makes this relatively easy) to reflect the actual data you'll be using. Sorry you haven't been able to get a hold of RIMES.

**Comment by Tedonze** [comment]
ok thank you i will make all as possible
