### ISSUE TITLE
clean code

### ISSUE THREAD

**Issue by coldsummerday** [herobd/handwriting_line_generation#18]
it is cool for your job for hw generation,
But,your code is full with if .....else.....

It seems do a lots of job for experiments
but...i feel difficult to understand the code  .
can you publish  a clean code for useful experimental settings
( feel sad for seeing code with   if ........else ......)
thanks

**Comment by herobd** [comment]
The many `if ... else` statements in the code is an artifact of my development style. As I'm developing and testing I like to keep my code backward compatible with all my previous experiments.

Sorry, I probably won't have time to clean out the `if ... else`s, but it should be easy for an outsider to clean up (if not exactly fast). Generally you'll see `if self.some_hyperparameter:`, in which case the unused branch can be discarded. You'd either need to look into the hyperparameters or just insert `print`s to find out which branch is used.

I should have used a consistent naming scheme for hyperparamters...

**Comment by herobd** [comment]
Okay, I did it. I've thrown out all the alternative methods and only left the method described in the paper.
I've left the full code in a new branch (`full-messy`) if you want to see the many things I had experimented with.
