### ISSUE TITLE
Questions about the data set

### ISSUE THREAD

**Issue by Fyzjym** [herobd/handwriting_line_generation#21]
It is a great paper, thank you for sharing the code.

I am curious, will the model work on word-level data sets? Or will the model work in a language where the strokes are connected together?

**Comment by herobd** [comment]
You should also check out SmartPatch:
https://github.com/MattAlexMiracle/SmartPatch
https://arxiv.org/abs/2105.10528

It is doing things at the word level and has better results.

**Comment by Fyzjym** [comment]
I agree with you，thank you for your reply.
