### ISSUE TITLE
Size of generated output?

### ISSUE THREAD

**Issue by SB2020-eye** [herobd/handwriting_line_generation#25]
What determines the size of the generated output when generating images using generate.py?

Is all output the size to which all input images are resized (ie, height of 64)? Or is there a way to have the output generated have the same size/resolution as the input images?

**Comment by herobd** [comment]
The output size is hardcoded into the model as 64 pixels. If you want it to be bigger, I'd recommend trying to run the output through Real-ESRGAN https://github.com/xinntao/Real-ESRGAN It has a Colab demo to make it easy.

**Comment by SB2020-eye** [comment]
Got it. Thanks!
