### ISSUE TITLE
Missing english text file

### ISSUE THREAD

**Issue by saurabh170** [herobd/handwriting_line_generation#3]
While training the GAN it is asking for english_text.txt file. Please provide some information on how to download that file and if we need to create that one than how to create?

**Comment by saurabh170** [comment]
is it the ground truth text file?

**Comment by herobd** [comment]
This is just a file with a lot of Enligh text. You can probably use anything, the size of it isn't terribly important. I think I used the American National Corpus, but I don't remember specifically. http://www.anc.org/
