### ISSUE TITLE
generate.py looping back to mode selection, not producing output..

### ISSUE THREAD

**Issue by abhidaberao** [herobd/handwriting_line_generation#30]
Here are the steps I took:

**input**
`python3 generate.py -c ./IAM_weights/IAMslant_noMask_charSpecSingleAppend_GANMedMT_autoAEMoPrcp2tightNewCTCUseGen_balB_hCF0.75_sMG/checkpoint-iteration175000.pth -d ./output1/out/jpg -s ./IAM_weights/IAMslant_noMask_charSpecSingleAppend_GANMedMT_autoAEMoPrcp2tightNewCTCUseGen_balB_hCF0.75_sMG/test_styles_175000.pkl`

**output**
`indexes/random interp/vae random/strech/author display/math/turk gen/from-to/umap-images/Random styles/help/quit?`
**input**
`from-to`

**output**
`image path 1?`
**input**
`./h1.jpg`
**output**
`image path 2?`
**input**
`./h2.jpg`

**output**
`text to generate?`
**input**
`hello!`

**output**
`indexes/random interp/vae random/strech/author display/math/turk gen/from-to/umap-images/Random styles/help/quit?`

**Comment by herobd** [comment]
Does the output directory `./output1/out/jpg` exist? I think it the image writing may fail silently.

**Comment by abhidaberao** [comment]
> Does the output directory `./output1/out/jpg` exist? I think it the image writing may fail silently.

Yes it did. I found out it was some problem on my WSL system. It is working fine on native windows now.
