### ISSUE TITLE
AttributeError: 'HWWithStyleTrainer' object has no attribute 'run'

### ISSUE THREAD

**Issue by Bird9000** [herobd/handwriting_line_generation#31]
hi great work there .I try to train handwriting recognition model with used command
HWR: `python train.py -c configs/cf_IAM_hwr_cnnOnly_batchnorm_aug.json`
but i got this error 
![image](https://user-images.githubusercontent.com/102358159/162017502-8c29c39f-5ace-4b23-982d-d875c62f31e1.png)

do I miss something?

**Comment by herobd** [comment]
Sorry about taking so long to get back to you. This was a bug caused when I renamed some functions. Pull down the latest and it should work.
