### ISSUE TITLE
About Train and Eval

### ISSUE THREAD

**Issue by Fyzjym** [herobd/handwriting_line_generation#32]
Hello,
Your work is fantastic. May I ask some questions?
#### About training:
Excuse me, did you use Lines-Text-Level data or Word-Level data during training with the IAM dataset?
#### About FID and GS assessment:
Excuse me, can the code for calculating FID and GS be shared?

**Comment by herobd** [comment]
It was line level. I did my own cropping to not get the weird cropping artifacts in the datasets line level images.

https://github.com/herobd/pytorch-fid-handwriting

**Comment by Fyzjym** [comment]
The answer solved my doubts.
Thank you very much.
