### ISSUE TITLE
How to generate new handwriting images by using generate.py in random module?

### ISSUE THREAD

**Issue by Marco-Ray** [herobd/handwriting_line_generation#33]
Hi, thanks for the excellent work! I have generate few handwriting images by using generate.py in **from-to module**, which is great! However, when I try to use **random** module, I get an error, which is **NameError: name 'getDataLoader' is not defined**. So I try to delete **#** before **line 13: from data_loader import getDataLoader**, and get a new error **FileNotFoundError: [Errno 2] No such file or directory: '../data/IAM/xmls\\m03-110.xml'**. But I do not find any xml files in repo.

**Comment by herobd** [comment]
Try the "R" random mode.
