### ISSUE TITLE
'style_extractor' error in generate.py

### ISSUE THREAD

**Issue by parsley22** [herobd/handwriting_line_generation#8]
Great paper! I'm trying to run 'generate.py'. I am using your pretrained snapshots (IAM_hwr_cnnonly...), and setting the two image paths using the f option, along with the text. 

I've checked, and the images and text seem to be loaded correctly. But I'm getting this error with the style extractor:

handwriting_line_generation\model\hw_with_style.py", line 782, in extract_style
    style = self.style_extractor(collapsed_image, collapsed_label)
TypeError: 'NoneType' object is not callable 

Thanks for the amazing work.

**Comment by herobd** [comment]
That's the snapshot for the pre-trained handwriting recognition, you want the `IAMslant_noMask_charSpecSingleAppend_GANMedMT_autoAEMoPrcp2tightNewCTCUseGen_balB_hCF0.75_sMG` one.

**Comment by parsley22** [comment]
Thanks for the quick reply. I think I may be missing something obvious (it's been a long week). When running generate.py with the  correct snapshot, how can I use my own images when running this?

**Comment by herobd** [comment]
If you want to use your own images as the source of the style use the `f` option, as I explained here https://github.com/herobd/handwriting_line_generation/issues/7#issuecomment-756889833
